// Choose which special level goes in which slot, and write data/bonus.js.
//
//   node scripts/gen-bonus.mjs
//
// A special level is offered after every fifth classic level. Slot 1 comes
// after classic level 5, slot 2 after level 10, and so on.
//
// ⚠ The special pool is NOT in difficulty order. Its par runs 24, 19, 23, 26,
// 28, 30, 41, 17 ... - the easiest board in all 2,596 sits at position 8. Hand
// the slots out in pool order and eight insertions in nine are *easier* than
// the classic level the player just beat, which is the opposite of the point.
// So the order is chosen here, once, at build time.
//
// The rule: aim each slot at 1.30x the hardest of the five classic levels just
// played, and spend the easiest board that clears that bar so the hard ones are
// still there later. The result ships as a fixed list - every player gets the
// same special level in the same slot, and nothing is decided at run time.
//
// ⚠ The bar is the local five, not the player's all-time hardest. Classic par
// stops climbing around level 35 and then wanders between 18 and 31 forever,
// with the odd 43 - so an all-time peak is a single outlier that the bar then
// never comes down from, and past slot 40 nothing in the pool can clear it.
//
// ⚠ And no "never go backwards" rule. The classic run does go backwards - it
// plateaus and wobbles - so a special track that only ever climbs runs off the
// top of the pool and every later slot falls short.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const load = (f) => {
  const w = {};
  new Function('window', readFileSync(join(ROOT, 'data', f), 'utf8'))(w);
  return w;
};

const w = Object.assign({}, load('levels-classic.js'), load('par-classic.js'),
                            load('levels-hard.js'), load('par-hard.js'));

const CLASSIC = w.LEVELS_CLASSIC, HARD = w.LEVELS_HARD;
const par = (table, i) => parseInt(table.substr(i * 2, 2), 36) || 0;
const colours = (raw, stripDepth) => {
  const s = stripDepth ? raw.slice(1) : raw;
  return new Set([...s].filter((c) => c !== '-')).size;
};

/** every fifth classic level gets an offer after it */
const EVERY = 5;
/** how much harder than anything the player has met the special one should be */
const AIM = 1.30;

/* ⚠ Cường dropped special level 2 - "level này k hay". 0-based here. */
const DROP = new Set([1]);

const pool = [];
for (let i = 0; i < HARD.length; i++) {
  if (DROP.has(i)) continue;
  pool.push({ i, par: par(w.PAR_HARD, i), col: colours(HARD[i], true) });
}
/* easiest first, so "the easiest board that still clears the bar" is a scan
   forward and the hard ones stay in reserve */
pool.sort((a, b) => a.par - b.par || a.col - b.col);

const slots = Math.min(pool.length, Math.floor(CLASSIC.length / EVERY));
const taken = new Array(pool.length).fill(false);
const out = [];
const bars = [];
let short = 0, pos = 0;

for (let s = 1; s <= slots; s++) {
  /* the hardest of the five they just played */
  let local = 0;
  for (let n = (s - 1) * EVERY; n < s * EVERY; n++) local = Math.max(local, par(w.PAR_CLASSIC, n));
  const want = local * AIM;
  bars.push(local);

  while (pos < pool.length && taken[pos]) pos++;
  if (pos >= pool.length) break;
  let k = pos;
  while (k < pool.length && (taken[k] || pool[k].par < want)) k++;

  /* ⚠ Nothing left that clears the bar: stop, do not spend what is left.
     About 500 boards in the pool sit at par ~33, which is *below* the bar once
     the classic run plateaus - they can never be a step up, only a step
     sideways dressed as an occasion. Better to run out of special levels at
     classic 7,500 than to hand out 1,088 that are not special. */
  if (k >= pool.length) { short = slots - s + 1; break; }
  taken[k] = true;
  out.push(pool[k].i);
}

/* Fixed-width base 36: 2,596 fits in three characters, and a fixed width means
   the reader is a substr rather than a split of a 10 kB string. */
const packed = out.map((i) => i.toString(36).padStart(3, '0')).join('');

writeFileSync(join(ROOT, 'data', 'bonus.js'),
`/* Generated by scripts/gen-bonus.mjs - do not edit by hand.
 *
 * Which special level fills which slot. Slot 1 is offered after classic level
 * ${EVERY}, slot 2 after level ${EVERY * 2}, and so on. Three base-36 digits per
 * slot, 0-based into LEVELS_HARD.
 *
 * ${out.length} slots, covering classic levels ${EVERY} to ${out.length * EVERY}.
 */
window.BONUS_ORDER = '${packed}';
`, 'utf8');

/* ------------------------------- report ------------------------------- */

const fmt = (n) => n.toLocaleString('vi-VN');
console.log(`data/bonus.js -> ${fmt(out.length)} suat, phu man co dien ${EVERY}..${fmt(out.length * EVERY)}`);
console.log(`  bo ${DROP.size} man ("k hay"), kho con ${fmt(pool.length)}`);
console.log(`  het man du kho sau suat ${fmt(out.length)}; ${fmt(pool.length - out.length)} man con lai khong dung`);
let hit = 0;
for (let s = 1; s <= out.length; s++) if (par(w.PAR_HARD, out[s - 1]) >= bars[s - 1] * AIM) hit++;
let up = 0;
for (let s = 1; s <= out.length; s++) if (par(w.PAR_HARD, out[s - 1]) > bars[s - 1]) up++;
console.log(`  dat muc +${((AIM - 1) * 100) | 0}%: ${(hit / out.length * 100).toFixed(1)}%   kho hon (bat ky bien do): ${(up / out.length * 100).toFixed(1)}%`);
for (const s of [1, 2, 3, 4, 6, 8, 12, 20, 100, 500, 1000, 2000, out.length]) {
  if (s > out.length) continue;
  const h = out[s - 1], p = par(w.PAR_HARD, h);
  console.log(`  suat ${String(s).padStart(4)} (sau man ${String(s * EVERY).padStart(5)}): ` +
    `par 5 man vua qua ${String(bars[s - 1]).padStart(2)} -> dac biet #${String(h + 1).padEnd(5)} ` +
    `par ${String(p).padStart(2)}  x${(p / bars[s - 1]).toFixed(2)}`);
}
